---
openapi: 3.0.1
info:
  title: API
  version: v1
components:
paths:
  "/teachers/:teacher_id/followed_students/:student_id":
    post:
      description: "A teacher follows a student"
      responses:
        200:
          description: "Success"
        404:
          description: "Student not found"
    delete:
      description: "A teacher unfollows a student"
      responses:
        200:
          description: "Success"
        404:
          description: "Student not found"
  "/teachers/:teacher_id/followed_students":
    get:
      description: Get a list of students followed by the specified teacher
      responses:
        200:
          description: "Success"
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: int
                      required: true
                    first_name:
                      type: string
                      required: true
                      example:
                    last_name:
                      type: string
                      required: true
                    gender:
                      type: string
                      enum: [male, female]
                      required: true
